import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import localFont from 'next/font/local';
import { Navbar } from '@/components/navbar';
import { Cursor } from '@/components/cursor';
import PageTransition from '@/components/page-transition';
import Footer from '@/components/footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const stardomFont = localFont({
    src: '../../public/fonts/Stardom-Regular.woff2',
    variable: '--font-stardom',
});

const satoshiFont = localFont({
    src: '../../public/fonts/Satoshi-Variable.woff2',
    variable: '--font-satoshi',
});

export const metadata: Metadata = {
    title: "CDX's Portfolio",
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                />
            </head>
            <body
                className={`${stardomFont.variable} ${satoshiFont.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar className="fixed left-10 top-1/2 transform -translate-y-1/2" />
                    <Cursor />
                    <PageTransition>

                        {children}

                        <Footer />
                    </PageTransition>
                </ThemeProvider>
            </body>
        </html>
    );
}
